import Head from 'next/head';
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillFacebook,
  AiFillGithub,
} from 'react-icons/ai';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { useState } from 'react';
import portrait from '../public/personal-portrait.png';
import yt_clone from '../public/projects/yt-clone-full.png';
import saas_landing_page from '../public/projects/saas-full.png';
import ecommerce from '../public/projects/ecommerce-full.png';
import coffee_laptop from '../public/coffee-laptop.jpg';
import code from '../public/code.png';
import design from '../public/design.png';
import consulting from '../public/consulting.png';
import Image from 'next/image';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  const popupMessage = (msg) => {
    alert(msg);
  }

  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>raccoonwannafly</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="font-mono py-5 flex justify-between dark:text-white">
            <h1 className="self-center text-xl">raccoonwannafly</h1>
            <ul className="nav__links flex items-center">
              <li className="rounded-md">
                <a className="p-3" href="#section__portfolio">
                  Portfolio
                </a>
              </li>
              <li className="rounded-md">
                <a className="p-3" href="#section__aboutme" onClick={() => popupMessage('Im updating this section :D')}>
                  About me
                </a>
              </li>
              <li className="rounded-md">
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="button__darkmode cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#">
                  Resume
                </a>
              </li>
            </ul>
          </nav>

          <div className="text-center p-10 py-10">
            <div className="person_portrait mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={portrait} layout="fill" objectFit="cover" alt="alt" />
            </div>
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Tài Nguyễn
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Front-end junior developer~
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Hi there👋. I&rsquo;m an enthusiastic and dedicated, self-taught
              react developer based in Vinh - Nghe An.
              <br />
              Dont by shy! Hit me up 👉 nctaiofficial@gmail.com
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a
                className="redirect link__github"
                href="https://github.com/raccoonwannafly/"
                target="_blank"
                rel="noreferrer">
                <AiFillGithub />
              </a>
              <a
                className="redirect link__linkedin"
                href="http://www.linkedin.com/in/tainguyencong"
                target="_blank"
                rel="noreferrer">
                <AiFillLinkedin />
              </a>
              <a className="redirect link__twitter">
                <AiFillTwitterCircle />
              </a>
              <a className="redirect link__facebook">
                <AiFillFacebook />
              </a>
            </div>
          </div>
        </section>

        <section id="section__skills" className="font-sans">
          <div>
            <h3 className="text-3xl underline decoration-2 text-center py-1 dark:text-white ">
              My tech skills
            </h3>
            <p className="text-xl text-center py-2 leading-8 text-gray-800 dark:text-gray-200">
              New in the industry, I&rsquo;m eager to learn and always strive to adapt to
              new technologies as well as building my portfolio, obtain new
              skills to add to my arsenal of techstack.
            </p>
            <br />
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-xl p-5 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} width={50} height={50} alt="alt" />
              <h2 className="text-xl font-medium pt-8 pb-2  ">
                Beautiful Designs
              </h2>
              <p className="text-xl py-2">
                Creating elegant designs suited for user needs following core
                design theory like color scheme, etc..
              </p>
              <h4 className="text-xl py-4 text-teal-600">Using</h4>
              <p className="text-xl text-gray-800 py-1">SASS / SCSS </p>
              <p className="text-xl text-gray-800 py-1">Bootstrap 5</p>
              <p className="text-xl text-gray-800 py-1">TailwindCSS</p>
              <p className="text-xl text-gray-800 py-1">Figma</p>
            </div>

            <div className="text-center shadow-xl p-5 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={50} height={50} alt="alt" />
              <h3 className="text-xl font-medium pt-8 pb-2 ">
                Code your dream project
              </h3>
              <p className="text-xl py-2">
                Do you have an idea for your next great website? Or a prototype
                to kickstart that project? Let&rsquo;s make it a reality.
              </p>
              <h4 className="text-xl py-4 text-teal-600">Using</h4>
              <p className="text-xl text-gray-800 py-1">
                React (Redux, Axios) / Vue (VueX)
              </p>
              <p className="text-xl text-gray-800 py-1">
                NodeJS (Express) / NextJS
              </p>
              <p className="text-xl text-gray-800 py-1">MongoDB / Sanity</p>
            </div>

            <div className="text-center shadow-xl p-5 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={50} height={50} alt="alt" />
              <h3 className="text-xl font-medium pt-8 pb-2 ">Teamplayer</h3>
              <p className="text-xl py-2">
                Looking for someone who&rsquo;s willing to contribute to your or
                your company&rsquo;s project with dedication and responsibility
                to drive your business forward? Look no further!
              </p>
              <h4 className="text-xl py-4 text-teal-600">What I offer</h4>
              <p className="text-xl text-gray-800 py-1">Communication</p>
              <p className="text-xl text-gray-800 py-1">Collaboration</p>
              <p className="text-xl text-gray-800 py-1">Open-minded</p>
              <p className="text-xl text-gray-800 py-1">Problem solving</p>
            </div>
          </div>
        </section>

        <section id="section__portfolio" className="font-sans">
          <h3 className="text-3xl underline decoration-2 text-center py-1 dark:text-white ">
            My portfolio
          </h3>

          <div className="projects__showcase xl:flex gap-10">
            {/* PROJECT ECOMMERCE */}
            <div className="text-center h-3/4 shadow-xl p-5 rounded-xl my-10  dark:bg-white flex-1">
              <div className="thumbnail__container overflow-hidden max-h-60">
                <a
                  href="https://ecommerce-sanity-git-main-raccoon-wannafly.vercel.app/"
                  target="_blank"
                  rel="noreferrer">
                  <Image
                    className="rounded-lg object-contain"
                    width={'100%'}
                    height={'100%'}
                    layout="responsive"
                    src={ecommerce}
                    alt="alt"
                  />
                </a>
              </div>
              <h2 className="text-xl font-medium pt-8 pb-2  ">ECOMMERCE</h2>
              <p className="py-2">
                A functional ecommerce storefront, allows user to add products to
                cart and remove from cart. Using{' '}
                <span className="font-bold">Sanity CMS</span> platform to manage
                data and <span className="font-bold">Next.js</span> for
                optimized coponent system. Enable{' '}
                <span className="font-bold">Stripe </span>
                payment using <span className="font-bold">Stripe API</span> for
                fast and straightforward checkout process for users.
              </p>
              <p className="py-2 font-bold">
                <a target="_blank" rel="noreferrer" href="https://ecommerce-sanity-git-main-raccoon-wannafly.vercel.app/">
                  Live URL
                </a>
              </p>
              <p className="py-2 font-bold">
                <a target="_blank" rel="noreferrer" href="https://github.com/raccoonwannafly/ecommerce-sanity">
                  Source code
                </a>
              </p>
            </div>

            {/* PROJECT LANDING PAGE */}
            <div className="text-center h-3/4 shadow-xl p-5 rounded-xl my-10 dark:bg-white flex-1">
              <div className="thumbnail__container overflow-hidden max-h-60">
                <a
                  href="https://solution-landing-page.netlify.app/"
                  target="_blank"
                  rel="noreferrer">
                  <Image
                    className="object-cover"
                    width={'50%'}
                    height={'100%'}
                    layout="responsive"
                    src={saas_landing_page}
                    alt="alt"
                  />
                </a>
              </div>
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                SAAS LANNDING PAGE
              </h3>
              <p className="py-2">
                A fully responsive Saas (software as a service) and simple
                landing page, built from a figma design sketch. Using orange
                color palettes to give off innovative vibe in order to build
                interests in custommers. Made easily and at on-demand delivering
                speed powered by <span className="font-bold">Bootstrap 5</span>.
              </p>
              <p className="py-2 font-bold">
                <a target="_blank" rel="noreferrer" href="https://solution-landing-page.netlify.app/">
                  Live URL
                </a>
              </p>
              <p className="py-2 font-bold">
                <a target="_blank" rel="noreferrer" href="https://github.com/raccoonwannafly/saas-landing-page">
                  Source code
                </a>
              </p>
            </div>

            {/* PROJECT YT CLONE */}
            <div className="text-center h-3/4 shadow-xl p-5 rounded-xl my-10 dark:bg-white flex-1">
              <div className="thumbnail__container overflow-hidden max-h-60">
                <a
                  href="https://yt-clone-raccoonwannafly.netlify.app/"
                  target="_blank"
                  rel="noreferrer">
                  <Image
                    className="object-cover object-top"
                    width={'100%'}
                    height={'100%'}
                    layout="responsive"
                    src={yt_clone}
                    alt="alt"
                  />
                </a>
              </div>
              <h3 className="text-lg font-medium pt-8 pb-2 ">YOUTUBE CLONE</h3>
              <p className="py-2">
                A simple YouTube clone webpage, fetching data from{' '}
                <span className="font-bold">Rapid API</span>, using{' '}
                <span className="font-bold">React</span> framework with{' '}
                <span className="font-bold">Axios</span> library to handle API
                calls and <span className="font-bold">Material UI</span>{' '}
                component library alongside{' '}
                <span className="font-bold">Emotion.sh</span> for styling.
                Allows users to search for videos, display channel page and
                watch the videos.
              </p>
              <p className="py-2 font-bold">
                <a target="_blank" rel="noreferrer" href="https://yt-clone-raccoonwannafly.netlify.app/">
                  Live URL
                </a>
              </p>
              <p className="py-2 font-bold">
                <a target="_blank" rel="noreferrer" href="https://github.com/raccoonwannafly/yt-clone">
                  Source code
                </a>
              </p>
            </div>
          </div>
        </section>

        {/* <section id="section__aboutme">
          <div className="">
            <div className="overflow-hidden w-full h-40">
            <Image src={coffee_laptop} alt="coffee_laptop"/>
            </div>

            <div class="flex">
              <div class="about__me flex-1">
                <p>Hi there :D,
In 2018 I started my junior year in college at HUTECH University of Technology in HCM City. I majored in IT because I was once told by one of my friends that if I would ever excel in any field, it&rsquo;d probably has something to do with computer. However due to personal financial issues I had to drop out a year later, which in total I have just a single year in college experience. Since then I started to work part-time at local coffee shop where I gained plenty of work experience service-wise.

I get to work with a lovely owner. She&rsquo;s had 10 years in real estate business, and opened a coffee shop for college students to work at. Its where I learned strong work ethics and time managing skill, since each staff works solo in their respective shift. Currently, I no longer work there and decided to pick up basic HTML, CSS, JavaScript in order to get employment in IT industry. Initially I went through FreeCodeCamp Responsive Web Design course, however midway through I dropped due to the fact that they lack certain key features for JavaScript ES6, mainly and arguably the most important: Strict mode.

After that I joined Wes Bos&rsquo;s 30 days JavaScript challenge, super comprehensive course and through that I gained more confidence in working with JavaScript and DOM! Overall after 3 months I&rsquo;ve done a few projects to build up my skills. If you&rsquo;re interested in what I&rsquo;ve built, check out my Portfolio or my Github. I&rsquo;m looking for an oppotunity to get started in front-end development profession, if you&rsquo;re interested in helping me landing my first IT job ^^, feel free to email me at: <a>nctaiofficial@gmail.com</a>
</p>
              </div>

              <div class="form__contact flex-1">

              </div>
            </div>
          </div>
        </section> */}
      </main>
    </div>
  );
}
